version: "3.8"
services:
  app:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html/:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app_project1.rule=Host(`app.project1.localhost`)"

networks:
  default:
    external: true
    name: traefik