version: "3.8"
services:
  app:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html/:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app_p2.rule=Host(`app.p2.localhost`)"

networks:
  default:
    name: OneFront
    external: true