version: "3.8"
services:
  app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app_project2.rule=Host(`app.project2.localhost`)"

networks:
  default:
    external: true
    name: traefik